image:
  # Allow using a local dev image.
  repository: "pilates"
  tag: "latest"
  pullPolicy: Never

imagePullSecrets: []

api:
  podDisruptionBudget:
    enabled: false

httpRoute:
  enabled: false
