// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostData,
  AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostErrors,
  AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostResponses,
  AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostData,
  AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostErrors,
  AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostResponses,
  CreateExerciseExercisesPostData,
  CreateExerciseExercisesPostErrors,
  CreateExerciseExercisesPostResponses,
  DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteData,
  DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteErrors,
  DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteResponses,
  DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteData,
  DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteErrors,
  DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteResponses,
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteData,
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors,
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses,
  GenerateLessonPlanLessonPlansPostData,
  GenerateLessonPlanLessonPlansPostErrors,
  GenerateLessonPlanLessonPlansPostResponses,
  GetAuthenticatedUserDetailsAuthUserGetData,
  GetAuthenticatedUserDetailsAuthUserGetResponses,
  GetExerciseExercisesExerciseIdGetData,
  GetExerciseExercisesExerciseIdGetErrors,
  GetExerciseExercisesExerciseIdGetResponses,
  GetExercisesExercisesGetData,
  GetExercisesExercisesGetResponses,
  GetLessonPlanLessonPlansLessonPlanIdGetData,
  GetLessonPlanLessonPlansLessonPlanIdGetErrors,
  GetLessonPlanLessonPlansLessonPlanIdGetResponses,
  GetLessonPlansLessonPlansGetData,
  GetLessonPlansLessonPlansGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  LoginAuthTokenPostData,
  LoginAuthTokenPostErrors,
  LoginAuthTokenPostResponses,
  RefreshAccessTokenAuthTokenRefreshPostData,
  RefreshAccessTokenAuthTokenRefreshPostErrors,
  RefreshAccessTokenAuthTokenRefreshPostResponses,
  UpdateExerciseExercisesExerciseIdPutData,
  UpdateExerciseExercisesExerciseIdPutErrors,
  UpdateExerciseExercisesExerciseIdPutResponses,
  UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutData,
  UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutErrors,
  UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutResponses,
  UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutData,
  UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutErrors,
  UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const loginAuthTokenPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginAuthTokenPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginAuthTokenPostResponses,
    LoginAuthTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/auth/token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Refresh Access Token
 */
export const refreshAccessTokenAuthTokenRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshAccessTokenAuthTokenRefreshPostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshAccessTokenAuthTokenRefreshPostResponses,
    RefreshAccessTokenAuthTokenRefreshPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/auth/token/refresh",
    ...options,
  });

/**
 * Get Authenticated User Details
 */
export const getAuthenticatedUserDetailsAuthUserGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAuthenticatedUserDetailsAuthUserGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAuthenticatedUserDetailsAuthUserGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/user",
    ...options,
  });

/**
 * Get Exercises
 */
export const getExercisesExercisesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetExercisesExercisesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetExercisesExercisesGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/exercises/",
    ...options,
  });

/**
 * Create Exercise
 */
export const createExerciseExercisesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateExerciseExercisesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateExerciseExercisesPostResponses,
    CreateExerciseExercisesPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/exercises/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Exercise
 */
export const getExerciseExercisesExerciseIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetExerciseExercisesExerciseIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetExerciseExercisesExerciseIdGetResponses,
    GetExerciseExercisesExerciseIdGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/exercises/{exercise_id}",
    ...options,
  });

/**
 * Update Exercise
 */
export const updateExerciseExercisesExerciseIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateExerciseExercisesExerciseIdPutData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateExerciseExercisesExerciseIdPutResponses,
    UpdateExerciseExercisesExerciseIdPutErrors,
    ThrowOnError
  >({
    url: "/exercises/{exercise_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Lesson Plans
 */
export const getLessonPlansLessonPlansGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetLessonPlansLessonPlansGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetLessonPlansLessonPlansGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/",
    ...options,
  });

/**
 * Generate Lesson Plan
 */
export const generateLessonPlanLessonPlansPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GenerateLessonPlanLessonPlansPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GenerateLessonPlanLessonPlansPostResponses,
    GenerateLessonPlanLessonPlansPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Lesson Plan
 */
export const deleteLessonPlanLessonPlansLessonPlanIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteLessonPlanLessonPlansLessonPlanIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses,
    DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors,
    ThrowOnError
  >({ url: "/lesson-plans/{lesson_plan_id}", ...options });

/**
 * Get Lesson Plan
 */
export const getLessonPlanLessonPlansLessonPlanIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLessonPlanLessonPlansLessonPlanIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLessonPlanLessonPlansLessonPlanIdGetResponses,
    GetLessonPlanLessonPlansLessonPlanIdGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/{lesson_plan_id}",
    ...options,
  });

/**
 * Add Set To Sequence
 */
export const addSetToSequenceLessonPlansSequencesSequenceIdSetsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostResponses,
    AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/sequences/{sequence_id}/sets",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Exercise Set
 */
export const deleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteResponses,
    DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteErrors,
    ThrowOnError
  >({ url: "/lesson-plans/sequences/{sequence_id}/sets/{set_id}", ...options });

/**
 * Update Exercise Set
 */
export const updateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutResponses,
    UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutErrors,
    ThrowOnError
  >({
    url: "/lesson-plans/sequences/{sequence_id}/sets/{set_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Add Sequence To Section
 */
export const addSequenceToSectionLessonPlansLessonPlanIdSequencesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostResponses,
    AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/{lesson_plan_id}/sequences",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Exercise Sequence
 */
export const deleteExerciseSequenceLessonPlansSequencesSequenceIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteResponses,
    DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteErrors,
    ThrowOnError
  >({ url: "/lesson-plans/sequences/{sequence_id}", ...options });

/**
 * Update Exercise Sequence
 */
export const updateExerciseSequenceLessonPlansSequencesSequenceIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).put<
    UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutResponses,
    UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutErrors,
    ThrowOnError
  >({
    url: "/lesson-plans/sequences/{sequence_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/health",
    ...options,
  });
