// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateExerciseExercisesPostData,
  CreateExerciseExercisesPostErrors,
  CreateExerciseExercisesPostResponses,
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteData,
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors,
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses,
  GenerateLessonPlanLessonPlansPostData,
  GenerateLessonPlanLessonPlansPostErrors,
  GenerateLessonPlanLessonPlansPostResponses,
  GetExerciseExercisesExerciseIdGetData,
  GetExerciseExercisesExerciseIdGetErrors,
  GetExerciseExercisesExerciseIdGetResponses,
  GetExercisesExercisesGetData,
  GetExercisesExercisesGetResponses,
  GetLessonPlanLessonPlansLessonPlanIdGetData,
  GetLessonPlanLessonPlansLessonPlanIdGetErrors,
  GetLessonPlanLessonPlansLessonPlanIdGetResponses,
  GetLessonPlansLessonPlansGetData,
  GetLessonPlansLessonPlansGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Exercises
 */
export const getExercisesExercisesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetExercisesExercisesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetExercisesExercisesGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/exercises/",
    ...options,
  });

/**
 * Create Exercise
 */
export const createExerciseExercisesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateExerciseExercisesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateExerciseExercisesPostResponses,
    CreateExerciseExercisesPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/exercises/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Exercise
 */
export const getExerciseExercisesExerciseIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetExerciseExercisesExerciseIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetExerciseExercisesExerciseIdGetResponses,
    GetExerciseExercisesExerciseIdGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/exercises/{exercise_id}",
    ...options,
  });

/**
 * Get Lesson Plans
 */
export const getLessonPlansLessonPlansGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetLessonPlansLessonPlansGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetLessonPlansLessonPlansGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/",
    ...options,
  });

/**
 * Generate Lesson Plan
 */
export const generateLessonPlanLessonPlansPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GenerateLessonPlanLessonPlansPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GenerateLessonPlanLessonPlansPostResponses,
    GenerateLessonPlanLessonPlansPostErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Lesson Plan
 */
export const deleteLessonPlanLessonPlansLessonPlanIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteLessonPlanLessonPlansLessonPlanIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses,
    DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors,
    ThrowOnError
  >({ url: "/lesson-plans/{lesson_plan_id}", ...options });

/**
 * Get Lesson Plan
 */
export const getLessonPlanLessonPlansLessonPlanIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLessonPlanLessonPlansLessonPlanIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetLessonPlanLessonPlansLessonPlanIdGetResponses,
    GetLessonPlanLessonPlansLessonPlanIdGetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/lesson-plans/{lesson_plan_id}",
    ...options,
  });
