// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://127.0.0.1:8000" | (string & {});
};

/**
 * AddSequenceToSectionRequest
 */
export type AddSequenceToSectionRequest = {
  section: LessonPlanSection;
  /**
   * Name
   */
  name: string;
  /**
   * Reps
   */
  reps: number;
  /**
   * Notes
   */
  notes: string;
};

/**
 * AddSequenceToSectionResponse
 */
export type AddSequenceToSectionResponse = {
  /**
   * Id
   */
  id: number;
};

/**
 * AddSetToSequenceRequest
 */
export type AddSetToSequenceRequest = {
  /**
   * Exercise Id
   */
  exercise_id: number;
  /**
   * Reps
   */
  reps: number;
  /**
   * Duration Seconds
   */
  duration_seconds: number;
  movement_variant: MovementVariant;
  /**
   * Equipment Variant
   */
  equipment_variant: Array<Equipment>;
};

/**
 * AddSetToSequenceResponse
 */
export type AddSetToSequenceResponse = {
  /**
   * Id
   */
  id: number;
};

/**
 * Body_login_auth_token_post
 */
export type BodyLoginAuthTokenPost = {
  /**
   * Grant Type
   */
  grant_type?: string | null;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
  /**
   * Scope
   */
  scope?: string;
  /**
   * Client Id
   */
  client_id?: string | null;
  /**
   * Client Secret
   */
  client_secret?: string | null;
};

/**
 * CreateExerciseRequest
 */
export type CreateExerciseRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  category: ExerciseCategory;
  difficulty: Difficulty;
  primary_muscle_group: MuscleGroup;
  starting_position: StartingPosition;
  /**
   * Movement Variants
   */
  movement_variants: Array<MovementVariant>;
  /**
   * Equipment Variants
   */
  equipment_variants: Array<Equipment>;
};

/**
 * CreateExerciseResponse
 */
export type CreateExerciseResponse = {
  /**
   * Id
   */
  id: number;
};

/**
 * Difficulty
 */
export type Difficulty = "BEGINNER" | "INTERMEDIATE" | "ADVANCED";

/**
 * Equipment
 */
export type Equipment =
  | "BALL"
  | "BAND"
  | "RING"
  | "ANKLE_WEIGHTS"
  | "HAND_WEIGHTS";

/**
 * Exercise
 */
export type Exercise = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  category: ExerciseCategory;
  difficulty: Difficulty;
  primary_muscle_group: MuscleGroup;
  starting_position: StartingPosition;
  /**
   * Movement Variants
   */
  movement_variants: Array<MovementVariant>;
  /**
   * Equipment Variants
   */
  equipment_variants: Array<Equipment>;
};

/**
 * ExerciseCategory
 */
export type ExerciseCategory =
  | "BREATH_WORK"
  | "STRETCH"
  | "MOBILITY"
  | "EFFORT";

/**
 * ExerciseSequence
 */
export type ExerciseSequence = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Sets
   */
  sets: Array<ExerciseSet>;
  /**
   * Reps
   */
  reps: number;
  /**
   * Notes
   */
  notes: string;
};

/**
 * ExerciseSet
 */
export type ExerciseSet = {
  /**
   * Id
   */
  id: number;
  exercise: Exercise;
  /**
   * Reps
   */
  reps: number;
  /**
   * Duration Seconds
   */
  duration_seconds: number;
  movement_variant: MovementVariant;
  /**
   * Equipment Variant
   */
  equipment_variant: Array<Equipment>;
};

/**
 * GenerateLessonPlanRequest
 */
export type GenerateLessonPlanRequest = {
  requirements: LessonPlanRequirements;
};

/**
 * GenerateLessonPlanResponse
 */
export type GenerateLessonPlanResponse = {
  /**
   * Id
   */
  id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LessonPlan
 */
export type LessonPlan = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Date
   */
  date: string;
  requirements: LessonPlanRequirements;
  status: LessonPlanStatus;
  /**
   * Warm Up
   */
  warm_up: Array<ExerciseSequence>;
  /**
   * Main Session
   */
  main_session: Array<ExerciseSequence>;
  /**
   * Cool Down
   */
  cool_down: Array<ExerciseSequence>;
};

/**
 * LessonPlanRequirements
 */
export type LessonPlanRequirements = {
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  target_difficulty: Difficulty;
  /**
   * Target Muscle Groups
   */
  target_muscle_groups: Array<MuscleGroup>;
  /**
   * Example Lesson Plan Ids
   */
  example_lesson_plan_ids?: Array<number>;
  /**
   * Available Equipment
   */
  available_equipment: Array<Equipment>;
  /**
   * User Prompt
   */
  user_prompt: string;
};

/**
 * LessonPlanSection
 */
export type LessonPlanSection = "WARM_UP" | "MAIN_SESSION" | "COOL_DOWN";

/**
 * LessonPlanStatus
 */
export type LessonPlanStatus = "PENDING_GENERATION" | "GENERATED" | "ERRORED";

/**
 * MovementVariant
 */
export type MovementVariant = "STANDARD" | "PULSE" | "HOLD";

/**
 * MuscleGroup
 */
export type MuscleGroup =
  | "CORE"
  | "GLUTES"
  | "HIP_FLEXORS"
  | "BACK_EXTENSORS"
  | "SHOULDERS"
  | "INNER_THIGHS"
  | "HAMSTRINGS"
  | "OBLIQUES"
  | "TRICEPS"
  | "CHEST";

/**
 * StartingPosition
 */
export type StartingPosition =
  | "SUPINE"
  | "PRONE"
  | "SIDE_LYING"
  | "SEATED"
  | "QUADRUPED"
  | "STANDING"
  | "KNEELING"
  | "PLANK"
  | "SIDE_KNEELING";

/**
 * TokenResponse
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * UpdateExerciseRequest
 */
export type UpdateExerciseRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  category: ExerciseCategory;
  difficulty: Difficulty;
  primary_muscle_group: MuscleGroup;
  starting_position: StartingPosition;
  /**
   * Movement Variants
   */
  movement_variants: Array<MovementVariant>;
  /**
   * Equipment Variants
   */
  equipment_variants: Array<Equipment>;
};

/**
 * UpdateExerciseSequenceRequest
 */
export type UpdateExerciseSequenceRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Reps
   */
  reps: number;
  /**
   * Notes
   */
  notes: string;
};

/**
 * UpdateExerciseSetRequest
 */
export type UpdateExerciseSetRequest = {
  /**
   * Reps
   */
  reps: number;
  /**
   * Duration Seconds
   */
  duration_seconds: number;
  movement_variant: MovementVariant;
  /**
   * Equipment Variant
   */
  equipment_variant: Array<Equipment>;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Full Name
   */
  full_name: string;
  /**
   * Email
   */
  email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type LoginAuthTokenPostData = {
  body: BodyLoginAuthTokenPost;
  path?: never;
  query?: never;
  url: "/auth/token";
};

export type LoginAuthTokenPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginAuthTokenPostError =
  LoginAuthTokenPostErrors[keyof LoginAuthTokenPostErrors];

export type LoginAuthTokenPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginAuthTokenPostResponse =
  LoginAuthTokenPostResponses[keyof LoginAuthTokenPostResponses];

export type RefreshAccessTokenAuthTokenRefreshPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/token/refresh";
};

export type RefreshAccessTokenAuthTokenRefreshPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshAccessTokenAuthTokenRefreshPostError =
  RefreshAccessTokenAuthTokenRefreshPostErrors[keyof RefreshAccessTokenAuthTokenRefreshPostErrors];

export type RefreshAccessTokenAuthTokenRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RefreshAccessTokenAuthTokenRefreshPostResponse =
  RefreshAccessTokenAuthTokenRefreshPostResponses[keyof RefreshAccessTokenAuthTokenRefreshPostResponses];

export type GetAuthenticatedUserDetailsAuthUserGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/auth/user";
};

export type GetAuthenticatedUserDetailsAuthUserGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetAuthenticatedUserDetailsAuthUserGetResponse =
  GetAuthenticatedUserDetailsAuthUserGetResponses[keyof GetAuthenticatedUserDetailsAuthUserGetResponses];

export type GetExercisesExercisesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/exercises/";
};

export type GetExercisesExercisesGetResponses = {
  /**
   * Response Get Exercises Exercises  Get
   *
   * Successful Response
   */
  200: Array<Exercise>;
};

export type GetExercisesExercisesGetResponse =
  GetExercisesExercisesGetResponses[keyof GetExercisesExercisesGetResponses];

export type CreateExerciseExercisesPostData = {
  body: CreateExerciseRequest;
  path?: never;
  query?: never;
  url: "/exercises/";
};

export type CreateExerciseExercisesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateExerciseExercisesPostError =
  CreateExerciseExercisesPostErrors[keyof CreateExerciseExercisesPostErrors];

export type CreateExerciseExercisesPostResponses = {
  /**
   * Successful Response
   */
  201: CreateExerciseResponse;
};

export type CreateExerciseExercisesPostResponse =
  CreateExerciseExercisesPostResponses[keyof CreateExerciseExercisesPostResponses];

export type GetExerciseExercisesExerciseIdGetData = {
  body?: never;
  path: {
    /**
     * Exercise Id
     */
    exercise_id: number;
  };
  query?: never;
  url: "/exercises/{exercise_id}";
};

export type GetExerciseExercisesExerciseIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetExerciseExercisesExerciseIdGetError =
  GetExerciseExercisesExerciseIdGetErrors[keyof GetExerciseExercisesExerciseIdGetErrors];

export type GetExerciseExercisesExerciseIdGetResponses = {
  /**
   * Successful Response
   */
  200: Exercise;
};

export type GetExerciseExercisesExerciseIdGetResponse =
  GetExerciseExercisesExerciseIdGetResponses[keyof GetExerciseExercisesExerciseIdGetResponses];

export type UpdateExerciseExercisesExerciseIdPutData = {
  body: UpdateExerciseRequest;
  path: {
    /**
     * Exercise Id
     */
    exercise_id: number;
  };
  query?: never;
  url: "/exercises/{exercise_id}";
};

export type UpdateExerciseExercisesExerciseIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateExerciseExercisesExerciseIdPutError =
  UpdateExerciseExercisesExerciseIdPutErrors[keyof UpdateExerciseExercisesExerciseIdPutErrors];

export type UpdateExerciseExercisesExerciseIdPutResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UpdateExerciseExercisesExerciseIdPutResponse =
  UpdateExerciseExercisesExerciseIdPutResponses[keyof UpdateExerciseExercisesExerciseIdPutResponses];

export type GetLessonPlansLessonPlansGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/lesson-plans/";
};

export type GetLessonPlansLessonPlansGetResponses = {
  /**
   * Response Get Lesson Plans Lesson Plans  Get
   *
   * Successful Response
   */
  200: Array<LessonPlan>;
};

export type GetLessonPlansLessonPlansGetResponse =
  GetLessonPlansLessonPlansGetResponses[keyof GetLessonPlansLessonPlansGetResponses];

export type GenerateLessonPlanLessonPlansPostData = {
  body: GenerateLessonPlanRequest;
  path?: never;
  query?: never;
  url: "/lesson-plans/";
};

export type GenerateLessonPlanLessonPlansPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateLessonPlanLessonPlansPostError =
  GenerateLessonPlanLessonPlansPostErrors[keyof GenerateLessonPlanLessonPlansPostErrors];

export type GenerateLessonPlanLessonPlansPostResponses = {
  /**
   * Successful Response
   */
  201: GenerateLessonPlanResponse;
};

export type GenerateLessonPlanLessonPlansPostResponse =
  GenerateLessonPlanLessonPlansPostResponses[keyof GenerateLessonPlanLessonPlansPostResponses];

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteData = {
  body?: never;
  path: {
    /**
     * Lesson Plan Id
     */
    lesson_plan_id: number;
  };
  query?: never;
  url: "/lesson-plans/{lesson_plan_id}";
};

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteError =
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors[keyof DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors];

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponse =
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses[keyof DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses];

export type GetLessonPlanLessonPlansLessonPlanIdGetData = {
  body?: never;
  path: {
    /**
     * Lesson Plan Id
     */
    lesson_plan_id: number;
  };
  query?: never;
  url: "/lesson-plans/{lesson_plan_id}";
};

export type GetLessonPlanLessonPlansLessonPlanIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLessonPlanLessonPlansLessonPlanIdGetError =
  GetLessonPlanLessonPlansLessonPlanIdGetErrors[keyof GetLessonPlanLessonPlansLessonPlanIdGetErrors];

export type GetLessonPlanLessonPlansLessonPlanIdGetResponses = {
  /**
   * Successful Response
   */
  200: LessonPlan;
};

export type GetLessonPlanLessonPlansLessonPlanIdGetResponse =
  GetLessonPlanLessonPlansLessonPlanIdGetResponses[keyof GetLessonPlanLessonPlansLessonPlanIdGetResponses];

export type AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostData = {
  body: AddSetToSequenceRequest;
  path: {
    /**
     * Sequence Id
     */
    sequence_id: number;
  };
  query?: never;
  url: "/lesson-plans/sequences/{sequence_id}/sets";
};

export type AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostError =
  AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostErrors[keyof AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostErrors];

export type AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostResponses = {
  /**
   * Successful Response
   */
  201: AddSetToSequenceResponse;
};

export type AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostResponse =
  AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostResponses[keyof AddSetToSequenceLessonPlansSequencesSequenceIdSetsPostResponses];

export type DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteData =
  {
    body?: never;
    path: {
      /**
       * Sequence Id
       */
      sequence_id: number;
      /**
       * Set Id
       */
      set_id: number;
    };
    query?: never;
    url: "/lesson-plans/sequences/{sequence_id}/sets/{set_id}";
  };

export type DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteError =
  DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteErrors[keyof DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteErrors];

export type DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    204: void;
  };

export type DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteResponse =
  DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteResponses[keyof DeleteExerciseSetLessonPlansSequencesSequenceIdSetsSetIdDeleteResponses];

export type UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutData = {
  body: UpdateExerciseSetRequest;
  path: {
    /**
     * Sequence Id
     */
    sequence_id: number;
    /**
     * Set Id
     */
    set_id: number;
  };
  query?: never;
  url: "/lesson-plans/sequences/{sequence_id}/sets/{set_id}";
};

export type UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutError =
  UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutErrors[keyof UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutErrors];

export type UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutResponses =
  {
    /**
     * Successful Response
     */
    204: void;
  };

export type UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutResponse =
  UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutResponses[keyof UpdateExerciseSetLessonPlansSequencesSequenceIdSetsSetIdPutResponses];

export type AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostData = {
  body: AddSequenceToSectionRequest;
  path: {
    /**
     * Lesson Plan Id
     */
    lesson_plan_id: number;
  };
  query?: never;
  url: "/lesson-plans/{lesson_plan_id}/sequences";
};

export type AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostError =
  AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostErrors[keyof AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostErrors];

export type AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostResponses =
  {
    /**
     * Successful Response
     */
    201: AddSequenceToSectionResponse;
  };

export type AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostResponse =
  AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostResponses[keyof AddSequenceToSectionLessonPlansLessonPlanIdSequencesPostResponses];

export type DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteData = {
  body?: never;
  path: {
    /**
     * Sequence Id
     */
    sequence_id: number;
  };
  query?: never;
  url: "/lesson-plans/sequences/{sequence_id}";
};

export type DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteError =
  DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteErrors[keyof DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteErrors];

export type DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteResponses =
  {
    /**
     * Successful Response
     */
    204: void;
  };

export type DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteResponse =
  DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteResponses[keyof DeleteExerciseSequenceLessonPlansSequencesSequenceIdDeleteResponses];

export type UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutData = {
  body: UpdateExerciseSequenceRequest;
  path: {
    /**
     * Sequence Id
     */
    sequence_id: number;
  };
  query?: never;
  url: "/lesson-plans/sequences/{sequence_id}";
};

export type UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutError =
  UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutErrors[keyof UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutErrors];

export type UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutResponse =
  UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutResponses[keyof UpdateExerciseSequenceLessonPlansSequencesSequenceIdPutResponses];

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
