// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://127.0.0.1:8000" | (string & {});
};

/**
 * CreateExerciseRequest
 */
export type CreateExerciseRequest = {
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  difficulty: Difficulty;
  primary_muscle_group: MuscleGroup;
  starting_position: StartingPosition;
};

/**
 * CreateExerciseResponse
 */
export type CreateExerciseResponse = {
  /**
   * Id
   */
  id: number;
};

/**
 * Difficulty
 */
export type Difficulty = "BEGINNER" | "INTERMEDIATE" | "ADVANCED";

/**
 * Exercise
 */
export type Exercise = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  difficulty: Difficulty;
  primary_muscle_group: MuscleGroup;
  starting_position: StartingPosition;
};

/**
 * ExerciseSequence
 */
export type ExerciseSequence = {
  /**
   * Name
   */
  name: string;
  /**
   * Notes
   */
  notes: string;
  /**
   * Sets
   */
  sets: Array<ExerciseSet>;
};

/**
 * ExerciseSet
 */
export type ExerciseSet = {
  exercise: Exercise;
  /**
   * Reps
   */
  reps: number;
  /**
   * Duration Seconds
   */
  duration_seconds: number;
};

/**
 * GenerateLessonPlanRequest
 */
export type GenerateLessonPlanRequest = {
  requirements: LessonPlanRequirements;
};

/**
 * GenerateLessonPlanResponse
 */
export type GenerateLessonPlanResponse = {
  lesson_plan: LessonPlan;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LessonPlan
 */
export type LessonPlan = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Date
   */
  date: string;
  /**
   * Warm Up
   */
  warm_up: Array<ExerciseSequence>;
  /**
   * Main Session
   */
  main_session: Array<ExerciseSequence>;
  /**
   * Cool Down
   */
  cool_down: Array<ExerciseSequence>;
};

/**
 * LessonPlanRequirements
 */
export type LessonPlanRequirements = {
  /**
   * Duration Minutes
   */
  duration_minutes: number;
  target_difficulty: Difficulty;
  /**
   * Target Muscle Groups
   */
  target_muscle_groups: Array<MuscleGroup>;
  /**
   * Example Lesson Plan Ids
   */
  example_lesson_plan_ids: Array<number>;
  /**
   * User Prompt
   */
  user_prompt: string;
};

/**
 * MuscleGroup
 */
export type MuscleGroup =
  | "CORE"
  | "GLUTES"
  | "HIP_FLEXORS"
  | "BACK_EXTENSORS"
  | "SHOULDERS"
  | "INNER_THIGHS"
  | "HAMSTRINGS"
  | "OBLIQUES"
  | "TRICEPS"
  | "CHEST";

/**
 * StartingPosition
 */
export type StartingPosition =
  | "SUPINE"
  | "PRONE"
  | "SIDE_LYING"
  | "SEATED"
  | "QUADRUPED"
  | "STANDING"
  | "KNEELING"
  | "PLANK"
  | "SIDE_KNEELING";

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetExercisesExercisesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/exercises/";
};

export type GetExercisesExercisesGetResponses = {
  /**
   * Response Get Exercises Exercises  Get
   *
   * Successful Response
   */
  200: Array<Exercise>;
};

export type GetExercisesExercisesGetResponse =
  GetExercisesExercisesGetResponses[keyof GetExercisesExercisesGetResponses];

export type CreateExerciseExercisesPostData = {
  body: CreateExerciseRequest;
  path?: never;
  query?: never;
  url: "/exercises/";
};

export type CreateExerciseExercisesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateExerciseExercisesPostError =
  CreateExerciseExercisesPostErrors[keyof CreateExerciseExercisesPostErrors];

export type CreateExerciseExercisesPostResponses = {
  /**
   * Successful Response
   */
  201: CreateExerciseResponse;
};

export type CreateExerciseExercisesPostResponse =
  CreateExerciseExercisesPostResponses[keyof CreateExerciseExercisesPostResponses];

export type GetExerciseExercisesExerciseIdGetData = {
  body?: never;
  path: {
    /**
     * Exercise Id
     */
    exercise_id: number;
  };
  query?: never;
  url: "/exercises/{exercise_id}";
};

export type GetExerciseExercisesExerciseIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetExerciseExercisesExerciseIdGetError =
  GetExerciseExercisesExerciseIdGetErrors[keyof GetExerciseExercisesExerciseIdGetErrors];

export type GetExerciseExercisesExerciseIdGetResponses = {
  /**
   * Successful Response
   */
  200: Exercise;
};

export type GetExerciseExercisesExerciseIdGetResponse =
  GetExerciseExercisesExerciseIdGetResponses[keyof GetExerciseExercisesExerciseIdGetResponses];

export type GetLessonPlansLessonPlansGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/lesson-plans/";
};

export type GetLessonPlansLessonPlansGetResponses = {
  /**
   * Response Get Lesson Plans Lesson Plans  Get
   *
   * Successful Response
   */
  200: Array<LessonPlan>;
};

export type GetLessonPlansLessonPlansGetResponse =
  GetLessonPlansLessonPlansGetResponses[keyof GetLessonPlansLessonPlansGetResponses];

export type GenerateLessonPlanLessonPlansPostData = {
  body: GenerateLessonPlanRequest;
  path?: never;
  query?: never;
  url: "/lesson-plans/";
};

export type GenerateLessonPlanLessonPlansPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GenerateLessonPlanLessonPlansPostError =
  GenerateLessonPlanLessonPlansPostErrors[keyof GenerateLessonPlanLessonPlansPostErrors];

export type GenerateLessonPlanLessonPlansPostResponses = {
  /**
   * Successful Response
   */
  201: GenerateLessonPlanResponse;
};

export type GenerateLessonPlanLessonPlansPostResponse =
  GenerateLessonPlanLessonPlansPostResponses[keyof GenerateLessonPlanLessonPlansPostResponses];

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteData = {
  body?: never;
  path: {
    /**
     * Lesson Plan Id
     */
    lesson_plan_id: number;
  };
  query?: never;
  url: "/lesson-plans/{lesson_plan_id}";
};

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteError =
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors[keyof DeleteLessonPlanLessonPlansLessonPlanIdDeleteErrors];

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponse =
  DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses[keyof DeleteLessonPlanLessonPlansLessonPlanIdDeleteResponses];

export type GetLessonPlanLessonPlansLessonPlanIdGetData = {
  body?: never;
  path: {
    /**
     * Lesson Plan Id
     */
    lesson_plan_id: number;
  };
  query?: never;
  url: "/lesson-plans/{lesson_plan_id}";
};

export type GetLessonPlanLessonPlansLessonPlanIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLessonPlanLessonPlansLessonPlanIdGetError =
  GetLessonPlanLessonPlansLessonPlanIdGetErrors[keyof GetLessonPlanLessonPlansLessonPlanIdGetErrors];

export type GetLessonPlanLessonPlansLessonPlanIdGetResponses = {
  /**
   * Successful Response
   */
  200: LessonPlan;
};

export type GetLessonPlanLessonPlansLessonPlanIdGetResponse =
  GetLessonPlanLessonPlansLessonPlanIdGetResponses[keyof GetLessonPlanLessonPlansLessonPlanIdGetResponses];
